xsctyaml.bbclass: introduce variable PYTHON_NATIVE_SITEPACKAGES_DIR to fix multilib issue
Issue: LINCD-2547

If enabling multilib feature for MACHINE "zcu102-zynqmp", there will be an error
when building device-tree package:

ERROR: device-tree-xilinx+gitAUTOINC+73e546e312-r0 do_create_yaml: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_create_yaml(d)
     0003:
File: 'sources/core/../meta-xilinx-tools/classes/xsctyaml.bbclass', lineno: 79, function: do_create_yaml
     0075:
     0076:python do_create_yaml() {
     0077:    import sys, os
     0078:    os.sys.path.append(os.path.join(d.getVar('RECIPE_SYSROOT_NATIVE'),d.getVar('PYTHON_SITEPACKAGES_DIR')[1::]))
 *** 0079:    import yaml
     0080:    yaml_dict = {}
     0081:
     0082:    appconfig = (d.getVar("YAML_APP_CONFIG", True) or "").split()
     0083:    if appconfig:
Exception: ModuleNotFoundError: No module named 'yaml'

This is because that the variable "PYTHON_SITEPACKAGES_DIR" will be a wrong path
in multilib.

In oe-core/meta/classes/python3-dir.bbclass, the assignment of this variable is:
PYTHON_SITEPACKAGES_DIR = "${libdir}/${PYTHON_DIR}/site-packages".
The libdir will be "/usr/lib64" when enbling multilib. But python3-pyyaml-native is
always installed to ${RECIPE_SYSROOT_NATIVE}/usr/lib/${PYTHON_DIR}/site-packages.
So python3 can't find yaml module.

Introduce PYTHON_NATIVE_SITEPACKAGES_DIR to point to ${libdir_native} (/usr/lib)
to fix this multilib issue.

Upstream-Status: Pending

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Robert Yang <liezhi.yang@windriver.com>