meta-xilinx-tools: delete ps from HOSTTOOLS
Issue: LINCD-3010

In some build environments(e.g. Fedora29), ps is not installed, so
this will trigger error as below:

ERROR: The following required tools (as specified by HOSTTOOLS) appear
to be unavailable in PATH, please install them in order to proceed:
ps

Since xsct will use ps in some special conditions, and it is not necessary
for external-hdf feature, so delete ps from HOSTTOOLS.

Upstream-Status: Inappropriate [WR Linux specific change]

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Robert Yang <liezhi.yang@windriver.com>